name: better_test_reporter
description: A CLI for generating a junit xml report from dart test json output and libraries for parsing test json into dev-friendly models
version: 0.1.1
homepage: https://github.com/Betterment/better_test_reporter

environment:
  sdk: ">=2.18.1 <3.0.0"

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.0
  json_serializable: ^6.3.2
  lints: ^2.0.0
  test: ^1.21.6
dependencies:
  args: ^2.3.1
  freezed_annotation: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  pub_semver: ^2.1.1
  xml: ^6.1.0

executables:
  report_to_junit:
