name: better_test_reporter
description: A CLI for generating a junit xml report from dart test json output and libraries for parsing test json into dev-friendly models
version: 0.0.1
homepage: https://github.com/Betterment/better_test_reporter

environment:
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.5
  freezed: ^1.1.0
  json_serializable: ^6.1.1
  lints: ^1.0.1
  test: ^1.19.5
dependencies:
  args: ^2.3.0
  freezed_annotation: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  pub_semver: ^2.1.0
  xml: ^5.3.1

executables:
  report_to_junit:
